# ===========================
# FRONTEND (React + Vite)
# ===========================

- task: NodeTool@0
  displayName: 'Install Node.js 18'
  inputs:
    versionSpec: '18.x'

- script: |
    cd frontend/devtaskhub-frontend
    npm install
    npm run build
  displayName: 'Build Frontend (React + Vite)'

- task: ArchiveFiles@2
  displayName: 'Zip Frontend Dist'
  inputs:
    # Usamos ruta absoluta desde el repo
    rootFolderOrFile: '$(Build.SourcesDirectory)/frontend/devtaskhub-frontend/dist'
    includeRootFolder: false           # 👈 clave: NO incluir carpeta dist
    archiveType: 'zip'
    archiveFile: '$(Build.ArtifactStagingDirectory)/frontend/frontend_zip.zip'
    replaceExistingArchive: true

# ===========================
# PUBLICAR ARTEFACTOS
# ===========================

- task: PublishBuildArtifacts@1
  displayName: 'Publish Backend Artifact'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/backend'
    artifactName: 'drop'
    publishLocation: 'Container'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Frontend Artifact'
  inputs:
    pathToPublish: '$(Build.ArtifactStagingDirectory)/frontend'
    artifactName: 'frontend'
    publishLocation: 'Container'
